# Generated by Django 4.2.29 on 2026-04-18 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_repository_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='release_date',
        ),
    ]
