# Generated by Django 4.2.29 on 2026-04-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_track_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='genre',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='track',
            name='tempo',
            field=models.FloatField(default=0),
        ),
    ]
