# Generated by Django 4.2.29 on 2026-04-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_track_genre_track_tempo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='genre',
        ),
        migrations.AddField(
            model_name='track',
            name='track_genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
